- analyzers/Nessus/Nessus.json
- analyzers/Nessus/nessus.py
- analyzers/Nessus/requirements.txt
Here is a new shiny Nessus analyser for Cortex.
Here is the list of configuration parameters:
- url: the nessus scanner URL
- login: the nessus scanner user name
- password: the nessus scanner password
- ca_bundle: an optional CA certs file for validating nessus scanner certificate
- allowed_networks: an optional list of networks (CIDR format), to restrict the scanner usage to those networks only
> initial import

- contrib/tests/suite.py
- contrib/tests/test_suite.py
So the tests working at python2, too. :)
> Use StringIO.StringIO() with python2

- .github/issue_template.md
- analyzers/FireHOLBlocklists/firehol_blocklists.py
There was a pretty obvious copy/paste mistake in the code. I don't really know, how that mistake made it through the testing. Merged an older commit or so?! Anyway, the fix + removed default value for path config. Think it's clearer if there's an error message telling the user no path was set instead of using one that is probably not there.
> Fixed mistake in blocklist script, added error on missing config

- analyzers/MISP/mispclient.py
This fixes a bug in MISP client, mentioned in #87, which throws a type error if config parameter certpath is empty.
Unfortunately, I currently don't have a proper testing evironment for this - can someone (@nadouani, @jeromeleonard) review/test this? Thank you.
> Fixes bug in MISP client

- analyzers/Virusshare/getHashes.sh
- analyzers/Virusshare/virusshare.py
I've added case insensitivity to the hash comparison within the analyzer. This is important because Virusshare stores all lowercase hashes, but if you compare an uppercase hash, it will always returns as not within the Virusshare dataset which can be dangerously incorrect.
I have benchmarked the comparison and found that the removal of the strip function actually improved the overall speed of the test when a line contains a single hash. Moving to the 'in' operator also allows for support of the UPX hash map file that has been created.
---
I've also added a simple bash script to fetch the hashes since I had issues with python version that is available. Bash is simpler and more or less always works as expected whereas python could apparently have issue that are harder to fix than (in this …
> Updates to Virusshare analyzer

- analyzers/MISP/mispclient.py
This should fix #90, totally overlooked that.
> MISP Analyzer: forgot to add same procedure if using just one MISP-Server

- analyzers/VxStreamSandbox/VxStreamSandbox_Hash_Report_Publuc_API.json
- analyzers/VxStreamSandbox/requirements.txt
- analyzers/VxStreamSandbox/vxstreamsandbox_analyzer.py
- thehive-templates/VxStreamSandbox_Hash_Report_Publuc_API_1_0/long.html
- thehive-templates/VxStreamSandbox_Hash_Report_Publuc_API_1_0/short.html
According to data from official site [1], VxStream Sandbox Public API
allows you to analyze:
- hash (OK, it works)
- filename (OK, it works)
- host / ip (some problems on API side for now)
- domain / fqdn (some problems on API side for now)
[1] https://www.hybrid-analysis.com/apikeys/info
> Added VxStream Sandbox (Hybrid Analysis) Analyzer

- analyzers/PhishTank/PhishTank_CheckURL.json
- analyzers/PhishTank/phishtank_checkurl.py
Follow up on #127. Based on develop branch.
* Replace http scheme with https due to changes in PhishTank API
* Fix error in summary() call as @saadkadhi pointed out
Hopefully closes #126
> Fix PhishTank analyzer

- analyzers/EmergingThreats/emergingthreats_analyzer.py
- thehive-templates/DomainTools_WhoisLookup_2_0/EmergingThreats_DomainInfo_1_0/long.html
- thehive-templates/DomainTools_WhoisLookup_2_0/EmergingThreats_IPInfo_1_0/long.html
Using the same template for Ip and Domain require existence check for particular section that are not present in both
> Fixed: hide empty panel from template

- analyzers/CuckooSandbox/cuckoosandbox_analyzer.py
- thehive-templates/CuckooSandbox_File_Analysis_Inet_1_0/long.html
- thehive-templates/CuckooSandbox_Url_Analysis_1_0/long.html
official cuckoo:  https://github.com/cuckoosandbox/cuckoo
modified cuckoo: https://github.com/doomedraven/cuckoo-modified
Thanks @norgalades for testing
> support both cuckoo versions

- analyzers/Censys/Censys.json
- analyzers/Censys/censys_analyzer.py
- analyzers/Censys/requirements.txt
- thehive-templates/Censys_1_0/long.html
- thehive-templates/Censys_1_0/short.html
Contents of long and short reports may have to be discussed.
Dependencies are censys python module and ofc cortexutils.
> Censys.io analyzer

- analyzers/SinkDB/SinkDB.json
- analyzers/SinkDB/requirements.txt
- analyzers/SinkDB/sinkdb.py
- thehive-templates/SinkDB_1_0/long.html
- thehive-templates/SinkDB_1_0/short.html
> Added SinkDB analyzer

- analyzers/MISPWarningLists/MISPWarningLists.json
- analyzers/MISPWarningLists/mispwarninglists.py
- analyzers/MISPWarningLists/requirements.txt
- thehive-templates/MISPWarningLists_1_0/long.html
- thehive-templates/MISPWarningLists_1_0/short.html
> Added MISP warning lists analyzer

- analyzers/Onyphe/Onyphe_Forward.json
- analyzers/Onyphe/Onyphe_Geolocate.json
- analyzers/Onyphe/Onyphe_Ports.json
- analyzers/Onyphe/Onyphe_Reverse.json
- analyzers/Onyphe/Onyphe_Threats.json
- analyzers/Onyphe/onyphe_analyzer.py
- analyzers/Onyphe/onyphe_api.py
- analyzers/Onyphe/requirements.txt
Hi,
We recently created analyzers for the Onyphe provider.
The implemented analyzers are:
- Open ports
- Geolocate
- Threatlists
- Reverse DNS lookup
- Forward DNS lookup
The required configuration for these analyzers is the Onyphe API key
> Add Onyphe analyzers

- analyzers/FireHOLBlocklists/firehol_blocklists.py
Hi,
I tried to use the FireHOL analyzer on last version but encountered the following error when executing it:
```bash
$ ./analyzers/FireHOLBlocklists/firehol_blocklists.py <<< '{"data":"1.2.3.4", "dataType":"ip", "config":{"blocklistpath": "/tmp/firehol"}}'
File "./analyzers/FireHOLBlocklists/firehol_blocklists.py", line 30
os.mkdir(self.path, 0700)
^
SyntaxError: invalid token
```
This pull request seems to fix it.
```bash
$ ./analyzers/FireHOLBlocklists/firehol_blocklists.py <<< '{"data":"1.2.3.4", "dataType":"ip", "config":{"blocklistpath": "/tmp/firehol"}}'
{"success": true, "summary": {"taxonomies": [{"level": "safe", "namespace": "Firehol", "predicate": "Blocklists", "value": "\"0 hit\""}]}, "artifacts": [], "full": {"hits": [], "count": 0}}
```
Best regards.
> Fix mode when creating FireHOL ipset directory

- analyzers/PayloadSecurity/PayloadSecurity_File_Analysis.json
- analyzers/PayloadSecurity/PayloadSecurity_File_Long_ReportTemplate.txt
- analyzers/PayloadSecurity/PayloadSecurity_Url_Analysis.json
- analyzers/PayloadSecurity/PayloadSecurity_Url_Long_ReportTemplate.txt
- analyzers/PayloadSecurity/payloadsecurity_analyzer.py
Hello,
I have created a Payload Security Sandbox Cortex analyzer.
It has been tested on private instance, but should be working on private cloud also.
It allows to submit file or URL from Cortex for sandbox analysis.
Also add report template for thehive integration.
Regards
> PayloadSecurity Analyzer

- analyzers/Virusshare/getHashes.sh
- analyzers/Yeti/requirements.txt
Modified the download script so it only downloads newly added hash files from virusshare, in order to conserve bandwidth for both sides.
> Download only new hash files

- analyzers/UnshortenLink/UnshortenLink.json
- analyzers/UnshortenLink/requirements.txt
- analyzers/UnshortenLink/unshortenlink.py
- thehive-templates/UnshortenLink_1_0/long.html
Hi,
UnshortenLink is an analyzer to find URL behind 301 or 302 redirects (tinyurl).
Example: you have one observable with dataType":"url" and data:"https://t.co/lw0xAzJFeL", it finds that the URL is "http://blog.thehive-project.org/2017/12/20/cerana-0-2-x-pack-auth-multi-source-dashboards/"
Ok?
Cheers,
Remi.
> add UnshortenLink analyzer

- analyzers/Malwares/Malwares_GetReport.json
- analyzers/Malwares/Malwares_Scan.json
- analyzers/Malwares/malwares.py
- analyzers/Malwares/malwares_api.py
- analyzers/Malwares/requirements.txt
- thehive-templates/Malwares_GetReport_1_0/long.html
- thehive-templates/Malwares_GetReport_1_0/short.html
- thehive-templates/Malwares_Scan_1_0/long.html
- thehive-templates/Malwares_Scan_1_0/short.html
New analyzer: malwares.com
Co-Authored-By: Arcuri Davide <dadokkio@gmail.com>
> New analyzer: malwares.com

- analyzers/MISPWarningLists/mispwarninglists.py
- analyzers/MISPWarningLists/requirements.txt
This should solves #197 by checking if the data is in IP and, if so, converting it from its string representation to an IpAddress object. It will do the same for the data from the warning lists to convert it to an IpNetwork object. This way, it is possible to simply check if the IP address is contained in a network and thus handle MISP lists containing networks.
> MISP WarningLists - Handling IP address lookup in CIDR IP ranges

- analyzers/StaxxSearch/requirements.txt
- analyzers/StaxxSearch/staxx-cortex.py
- analyzers/StaxxSearch/staxx.json
- thehive-templates/staxx_1_0/long.html
- thehive-templates/staxx_1_0/short.html
https://github.com/TheHive-Project/Cortex-Analyzers/issues/180
Please review my analyzer.
> Develop branch, add Staxx Analyzer

- analyzers/EmlParser/Eml_Parser.json
- analyzers/EmlParser/parse.py
- analyzers/EmlParser/requirements.txt
- thehive-templates/Eml_Parser_1_0/long.html
- thehive-templates/Eml_Parser_1_0/short.html
Same as MsgParser but for ```.eml``` file
> Eml Parser analyzer

- analyzers/DShield/DShield_lookup.json
- analyzers/DShield/DShield_lookup.py
- analyzers/DShield/DShield_lookup.report_template
- analyzers/DShield/requirements.txt
Being an ISC Handler, I had to write an analyzer for DShield! Comments are welcome!
> New analyzer: DShield

- analyzers/PhishingInitiative/PhishingInitiative_Scan.json
- analyzers/PhishingInitiative/phishinginitiative_scan.py
- thehive-templates/PhishingInitiative_Scan_1_0/long.html
- thehive-templates/PhishingInitiative_Scan_1_0/short.html
Hi,
a Phishing Initiative analyzer exists to lookup if an URL has already been analyzed. This analyzer permits to submit an URL for analyzing.
Ok?
Cheers,
Remi.
> add Phishing Initiative Scan analyzer.

- analyzers/RecordedFuture/RecordedFuture_risk.json
- analyzers/RecordedFuture/recordedfuture.py
- analyzers/RecordedFuture/requirements.txt
- thehive-templates/RecordedFuture_risk_1_0/long.html
- thehive-templates/RecordedFuture_risk_1_0/short.html
This pull request adds an analyzer for RecordedFuture. It was requested in #102.
The analyzer queries the RecordedFuture API to pull the risk summary and displays the number of "evidence details" and the risk score within the short view. The level of the score taxonomy depends on the reported "criticallity": 0 safe, 1 info, 2 suspicious, >=3 malicious  
A summary and the "Triggered Risk Rules" is displayed within the long view. A click on the "Intel Card" button will open a new tab with the corresponding intel card within the RecordedFuture web app.
> Add RecordedFuture Analyzer

- thehive-templates/URLhaus_1_0/long.html
I made a typo in URLhaus's report template (long.html). So let me fix it.
> Fix a typo in URLhaus's long.html

- analyzers/Onyphe/Onyphe_Datascan.json
- analyzers/Onyphe/Onyphe_Inetnum.json
- analyzers/Onyphe/onyphe_analyzer.py
- thehive-templates/Onyphe_Datascan_1_0/long.html
- thehive-templates/Onyphe_Datascan_1_0/short.html
- thehive-templates/Onyphe_Inetnum_1_0/long.html
- thehive-templates/Onyphe_Inetnum_1_0/short.html
> Add Datascan and Inetnum flavors

- analyzers/URLhaus/URLhaus.py
I noticed that GSB value is not retrieved in json causing "index out of range" error.
This fix checks if fields is available, otherwise go ahead.
If this field is not available anymore we can skip it and remove also from template long. I don't find documentation about this.
Online: 
The Hive:
Before the fix:
`{
"errorMessage": "Invalid output\nTraceback (most recent call last):\n File \"URLhaus/URLhaus_analyzer.py\", line 50, in <module>\n URLhausAnalyzer().run()\n File \"URLhaus/URLhaus_analyzer.py\", line 23, in run\n 'results': self.search(self.get_data())\n File \"URLhaus/URLhaus_analyzer.py\", line 17, in search\n return URLhaus(indicator).search()\n File \"/opt/Cortex-Analyzers/analyzers/URLhaus/URLhaus.py\", line 42, in search\n return self.parse(res)\n File …
> fix in case GSB value is missing

- analyzers/Fortiguard/Fortiguard_URLCategory.json
- analyzers/Fortiguard/urlcategory.py
The fortiguard analzer didn't accept fqdns. This fix changes that.
> Fix for Fortiguard to handle FQDNs as well as domains and urls

- analyzers/Cyberprotect/CyberprotectAnalyzer.py
- analyzers/Cyberprotect/Cyberprotect_ThreatScore.json
- analyzers/Cyberprotect/requirements.txt
- thehive-templates/Cyberprotect_ThreatScore/long.html
- thehive-templates/Cyberprotect_ThreatScore/short.html
> New analyzer : Cyberprotect ThreatScore

- analyzers/Patrowl/.gitignore
- analyzers/Patrowl/Patrowl_GetReport.json
- analyzers/Patrowl/README.md
- analyzers/Patrowl/patrowl.py
- analyzers/Patrowl/requirements.txt
- analyzers/Patrowl/templates/Patrowl_GetReport_long.html
- analyzers/Patrowl/templates/Patrowl_GetReport_short.html
Hi all,
Here is a proposal for an analyzer dealing with a Patrowl platform (see https://patrowl.io). Don't hesitate to reach me if you have any question or suggestion.
-- Nicolas
> Adding Patrowl analyzer

- thehive-templates/Fortiguard_URLCategory_2_1/long.html
Per issue https://github.com/TheHive-Project/Cortex-Analyzers/issues/345, request reclassification URL changed. Fixing report to reflect new URL.
> Fix Fortiguard reclassification request URL

- analyzers/EmlParser/parse.py
- thehive-templates/EmlParser_1_1/long.html
Made small changes to how headers are parsed, storing in a dict rather than list.
Updated long template to better display the headers.
> Improvement: Eml_Parser Analyzer & Template

- analyzers/Umbrella/Umbrella.py
- analyzers/Umbrella/Umbrella_Report.json
- analyzers/Umbrella/requirements.txt
- thehive-templates/Umbrella_Report_1_0/long.html
- thehive-templates/Umbrella_Report_1_0/short.html
Umbrella Analyzer currently supports pulling a list of most recent "hits" on a specified domain.
Analyzer utilizes the [Cisco Umbrella Reporting API](https://docs.umbrella.com/umbrella-api/docs/reporting-destinations-most-recent-requests).
Address issue #385
> Analyzer/Umbrella & Templates

- analyzers/IBMXForce/IBMXForce_Lookup.json
- analyzers/IBMXForce/ibmxforce_lookup.py
Hi guys, as we were struggling during testing this plug-in, I added certificate verification options. And to actually use the plug-in we require proxy support. So hereby a pull request for adding both these features.
If there is anything not compliant to any standards, let me know so I can adjust it.
> Additional features for IBM X-force plug-in

- analyzers/MISP/requirements.txt
MISP analyzer will not work properly without enum package
It's not a built-in package in ubuntu
> fix the lack of dependency called enum in ubuntu 16.04

- analyzers/BackscatterIO/BackscatterIO_Enrichment.json
- analyzers/BackscatterIO/BackscatterIO_GetObservations.json
- analyzers/BackscatterIO/backscatter-io.py
- analyzers/BackscatterIO/requirements.txt
- thehive-templates/BackscatterIO_Enrichment_1_0/long.html
- thehive-templates/BackscatterIO_Enrichment_1_0/short.html
- thehive-templates/BackscatterIO_GetObservations_1_0/long.html
- thehive-templates/BackscatterIO_GetObservations_1_0/short.html
Hi! I run Backscatter.io where we collect information about mass-scanning conducting on the Internet. This analyzer brings observations and enrichment data directly into TheHive and Cortex. I've tested various data-types in both systems with success. Apart from an API key, nothing else is required. Please let me know if there's anything needed from me to merge this!
> New analyzer: Backscatter.io

- analyzers/AbuseIPDB/AbuseIPDB.json
- analyzers/AbuseIPDB/abuseipdb.py
- analyzers/AbuseIPDB/requirements.txt
> Added AbuseIPDB analyzer

- analyzers/CuckooSandbox/cuckoosandbox_analyzer.py
- thehive-templates/CuckooSandbox_File_Analysis_Inet_1_0/long.html
- thehive-templates/CuckooSandbox_Url_Analysis_1_0/long.html
Analyzer
N/A
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| Cortex Analyzer Name      | CuckooSandbox Analyzer
| Cortex Analyzer Version   | 1.0
| Cortex Version            |  2.1.3-1
The current Cuckoo Sandbox reports do not fully function with 2.0.6 Cuckoo Reports. Instead of using just hosts for the report data, we need to use domains to retrieve ip/domain combination.
The solution is to update the analyzer and report templates to properly show the report data.
I have a fix for the solution however it would also then be nice to extract the observables from the newly added ip/domain combinations.
Here is what a report currently looks with Cuckoo 2.0.6:
And this is after the analyzer and report fix:
> Updating Cuckoo Analyzer/Report Templates

- analyzers/SoltraEdge/Soltra_search.json
- analyzers/SoltraEdge/requirements.txt
- analyzers/SoltraEdge/soltra.py
- thehive-templates/SoltraEdge_1_0/long.html
- thehive-templates/SoltraEdge_1_0/short.html
Referencing #264 - Soltra Edge Analyzer.
Added own TLP "classifier" to check the TLP set when running the analyzer and TLP for each object received from the Soltra API. If an object contains a TLP higher than searched for, the object is popped, and content is redacted.
Added modal view to show relations in frontend view. (To not overflow the main-view with data the modal was added as an separate view)
> Added SoltraEdge Analyzer

- analyzers/TalosReputation/TalosReputation.json
- analyzers/TalosReputation/TalosReputation.py
- analyzers/TalosReputation/requirements.txt
- thehive-templates/TalosReputation_1_0/long.html
- thehive-templates/TalosReputation_1_0/short.html
Fixes #426 
Created an analyzer to query Cisco Talos Intelligence for IP spam reputation
> New analyzer: Talos Reputation

- analyzers/Crtsh/crtshquery.py
- thehive-templates/Crt_sh_Transparency_Logs_1_0/long.html
Updated crt.sh analyzer to display SHA-1 fingerprint and updated long report. Additionally added manual artifact parsing,
> Crtsh updates

- analyzers/DNSSinkhole/DNSSinkhole.json
- analyzers/DNSSinkhole/dnssinkhole.py
- analyzers/DNSSinkhole/requirements.txt
- thehive-templates/DNSSinkhole_1_0/long.html
- thehive-templates/DNSSinkhole_1_0/short.html
Analyzer for query DNSSinkhole installed locally (ex. using BIND)
> DNSSinkhole analyzer

- utils/analyzer-runlocal.py
A quick wrapper utility to make it easier to run an Analyzer locally, particularly in development
For example
```
(venv) ndejong@dev:~/Cortex-Analyzers$ ./utils/analyzer-runlocal.py -a analyzers/DShield/DShield_lookup.py -j /tmp/job.json | jq .
analyzer: DShield_lookup.py
job_id:   20190423Z152549-35eb0b4b
job_path: /tmp/analyzer-runlocal/20190423Z152549-35eb0b4b
command:  analyzers/DShield/DShield_lookup.py /tmp/analyzer-runlocal/20190423Z152549-35eb0b4b
runtime:  1.969221830368042
{
"success": true,
"summary": {
"taxonomies": [
{
"level": "malicious",
"namespace": "DShield",
"predicate": "Score",
"value": "1131 count(s) / 561 attack(s) / 2 threatfeed(s)"
}
]
},
...
(venv) ndejong@dev:~/Cortex-Analyzers$ cat /tmp/job.json 
{
"dataType": "ip",
"data": "1.1.1.1",
}
```
> Utility to make running an Analyzer locally easier, helpful in development

- analyzers/IBMXForce/README
- analyzers/IBMXForce/ibmxforce_lookup.py
it fixes https://github.com/TheHive-Project/Cortex-Analyzers/issues/487
Thanks @csoc49 for reporting
Thanks @ssstonebraker for found fix
At the time analyzer was written that slash was needed :)
> remove extra slash

- analyzers/GoogleVisionAPI/GoogleVisionAPI_WebDetection.json
- analyzers/GoogleVisionAPI/GoogleVisionAPI_WebDetection.py
- analyzers/GoogleVisionAPI/requirements.txt
- thehive-templates/GoogleVisionAPI_WebDetection_1_0_0/long.html
- thehive-templates/GoogleVisionAPI_WebDetection_1_0_0/short.html
Hi,
I just finished to develop a new analyser based on the Google Cloud API Vision.
This analyser accept an image via an url or directly with the file and ask this API in order to get a list of website using this image and look alike image.
It can be usefull for data leak or to find phishing web site using known images.
> New analyser : Google Vision API

- responders/QRadarAutoClose/QRadarAutoClose.json
- responders/QRadarAutoClose/QRadarAutoClose.py
- responders/QRadarAutoClose/README.md
- responders/QRadarAutoClose/requirements.txt
Hi,
I want to share with you a responder that i wrote in python. He is working on my hive platform so I believe it's ready to use.
The main purpose of this responder is to close in one clic a QRadar offense from a TheHive case.
How it works:
Installation and configuration:
-Intall it in your Cortex Analyzers folder, in the responder section
-On Cortex WebUI, configure your QRadar console URL, an API key (service token), and a certificate if needed.
Use It:
-On TheHive, provide to your case the related QRadar offense ID in a customfield "externalReferences" (this have to be the customfield Internal Reference). I recommend to automatically fulfill via script this customfield when importing offenses as alert
-Clic the responder, and it will automagically close the offense in QRadar. That's …
> Responder QRadarAutoClose

- analyzers/Fortiguard/urlcategory.py
This PR addresses the issue #493 by handling "-" as a possible character in the categories names
> Fix category parsing forom Fortiguard URLCategory

- responders/FalconCustomIOC/requirements.txt
Removed python builtins from `responders/FalconCustomIOC/requirements.txt`. These throw error messages during install with `pip install -U -r requirements.txt`.
Fix for issue 509
> removed python builtins from requirements.txt

- analyzers/Umbrella/Umbrella.py
query_limit gets error if no data provided. The default value 20 must be the second parameter, not the third (currently the default is None, and the str(None) is cracking)
> Umbrella analyzer: query_limit: error if no data provided

- analyzers/URLhaus/URLhaus_analyzer.py
Fix when hash not found, due to an unexpected return from urlhaus.
In this example the hash is not found but api returns ok:
Then in the short report the label is wrong:
Now returns the expected behavior:
> fix when hash not found

- analyzers/IPinfo/IPinfo_Details.json
- analyzers/IPinfo/IPinfo_Hosted_Domains.json
- analyzers/IPinfo/ipinfo.py
- analyzers/IPinfo/ipinfo_analyzer.py
- analyzers/IPinfo/requirements.txt
- thehive-templates/IPinfo_Details_1.0/long.html
- thehive-templates/IPinfo_Details_1.0/short.html
- thehive-templates/IPinfo_Hosted_Domains_1.0/long.html
- thehive-templates/IPinfo_Hosted_Domains_1.0/short.html
> Add IPinfo analyzer

- analyzers/EmailRep/EmailRep.json
- analyzers/EmailRep/emailrep.py
- analyzers/EmailRep/emailrep_analyzer.py
- analyzers/EmailRep/requirements.txt
- thehive-templates/EmailRep_1_0/long.html
- thehive-templates/EmailRep_1_0/short.html
> add Emailrep analyzer

- analyzers/Abuse_Finder/requirements.txt
This change is not enough (of course), it needs this PR to be merged :
https://github.com/certsocietegenerale/abuse_finder/pull/3
> Abuse_Finder : Add support to Python3.6

- responders/Wazuh/requirements.txt
- responders/Wazuh/wazuh.json
- responders/Wazuh/wazuh.py
Add Wazuh responder with initial capability to perform firewall drop for specified IP.
Requires the following custom fields to be present in a case (to perform correlation and initiate Wazuh Active Response):
`agent_id`
`alert_id`
`rule_id`
> Add Wazuh responder

- responders/DomainToolsIris_CheckMaliciousTags/DomainToolsIris_CheckMaliciousTags.json
- responders/DomainToolsIris_CheckMaliciousTags/domaintoolsiris_responder.py
DomainTools check for malicious tags depending on iris tags from DomainTools and add a tag to artifact and case.
>  DomainTools Iris - Malicious Tags Responder

- responders/DomainToolsIris_AddRiskyDNSTag/DomainToolsIris_AddRiskyDNSTag.json
- responders/DomainToolsIris_AddRiskyDNSTag/domaintoolsiris_responder.py
DomainTools add risky DNS tag to artifact and case depending on risk score tag from DomainTools.
>  DomainTools Iris - Risky DNS Responder

- responders/Minemeld/minemeld.json
- responders/Minemeld/minemeld.py
- responders/Minemeld/requirements.txt
Add Minemeld responder to allow for submission of indicators to Palo Alto Minemeld.
> Add Palo Alto Minemeld Responder

- analyzers/TeamCymruMHR/TeamCymruMHR.json
- analyzers/TeamCymruMHR/TeamCymruMHR.py
- analyzers/TeamCymruMHR/requirements.txt
- thehive-templates/TeamCymruMHR_1_0/long.html
- thehive-templates/TeamCymruMHR_1_0/short.html
Add TeamCymru Malware Hash Registry Analyzer to allow for submission of hash for last_seen and detection percentage.
Related to: 
https://github.com/TheHive-Project/Cortex-Analyzers/issues/576
> Add TeamCymruMHR Analyzer

- analyzers/Autofocus/AUTOFOCUS_GetSampleAnalysis.json
- analyzers/Autofocus/AUTOFOCUS_SearchIOC.json
- analyzers/Autofocus/AUTOFOCUS_SearchJSON.json
- analyzers/Autofocus/analyzer.py
- analyzers/Autofocus/requirements.txt
> Autofocus analyzer v1

- analyzers/SpamhausDBL/SpamhausDBL.json
- analyzers/SpamhausDBL/requirements.txt
- analyzers/SpamhausDBL/spamhausdbl.py
- thehive-templates/SpamhausDBL_1_0/long.html
- thehive-templates/SpamhausDBL_1_0/short.html
Related to https://github.com/TheHive-Project/Cortex-Analyzers/issues/436
> Add Spamhaus DBL analyzer

- analyzers/ThreatResponse/ThreatResponse.json
- analyzers/ThreatResponse/ThreatResponse.py
- analyzers/ThreatResponse/long.html
- analyzers/ThreatResponse/requirements.txt
Initial Release of the Cisco Threat Response Analyzer
Issue Reference: https://github.com/TheHive-Project/Cortex-Analyzers/issues/592
> Cisco Threat Response Analyzer

- analyzers/ThreatGrid/ThreatGrid.json
- analyzers/ThreatGrid/ThreatGrid.py
- analyzers/ThreatGrid/long.html
- analyzers/ThreatGrid/requirements.txt
Initial Release of the Cisco Threat Grid analyzer
Issue Reference: https://github.com/TheHive-Project/Cortex-Analyzers/issues/146
> Cisco Threat Grid Analyzer

- responders/Redmine/Redmine_Issue.json
- responders/Redmine/redmine.py
- responders/Redmine/redmine_client.py
- responders/Redmine/requirements.txt
Hi,
Here is a first draft for a responder used to create an issue in the Redmine ticketing system from a case. It will use the case title as the issue subject and the case description as the issue body. It will also use the case severity as the issue priority with the following mapping:
| case   | issue  |
|--------|--------|
| low    | low    |
| medium | normal |
| high   | high   |
To set it up in Cortex, you will need:
* To define a user to allow Cortex to connect to Redmine and with access on the various project in which issues should be created
* Define three custom fields in TheHive that will be used to select the project, the tracker and the assignee of the issue (the latest being optional) Those fields can be let free or can be custom fields with preset values
This is a minimal …
> Redmine responder

- responders/AMPforEndpoints/AMPforEndpoints.py
- responders/AMPforEndpoints/AMPforEndpoints_IsolationStart.json
- responders/AMPforEndpoints/AMPforEndpoints_IsolationStop.json
- responders/AMPforEndpoints/AMPforEndpoints_MoveGUID.json
- responders/AMPforEndpoints/AMPforEndpoints_SCDAdd.json
- responders/AMPforEndpoints/AMPforEndpoints_SCDRemove.json
- responders/AMPforEndpoints/requirements.txt
Initial Release of the Cisco AMP for Endpoints Responder
Issue Reference:
https://github.com/TheHive-Project/Cortex-Analyzers/issues/593
> Cisco AMP for Endpoints Responder

- analyzers/IntezerCommunity/IntezerCommunity.json
- analyzers/IntezerCommunity/intezer_community.py
- analyzers/IntezerCommunity/requirements.txt
- thehive-templates/IntezerCommunity_1_0/long.html
- thehive-templates/IntezerCommunity_1_0/short.html
related to issue #504.
Forgive me but I don't use The Hive, I'm just a Cortex user and, sincerely, I didn't get the chance to test templates. However I followed other templates scheme. If you can check if it works before merging it would help. thanks
> added IntezerCommunity analyzer

- analyzers/Threatcrowd/threatcrowd_analyzer.py
Hi,
ThreatCrowd analyzer was not working for me... 
requests.get was complaining about - _get() takes exactly 1 argument (2 given)_, because "params" was missing. 
Hope this PR was done in the right manner, because it's my first ever PR.
Let me know if I did something wrong.
> [ThreatCrowd ] Fixing Unexpected Error: get() takes exactly 1 argument (2 given)

- analyzers/TalosReputation/TalosReputation.py
Perform initial request using requests.Session() in order to obtain initial session cookie, subsequent API requests will use cookie and store response cookie which rolls with each request.
> Issue #521 Fix - Talos Analyzer No Longer Works

- analyzers/MalwareBazaar/MalwareBazaar.json
- analyzers/MalwareBazaar/MalwareBazaar_analyzer.py
- analyzers/MalwareBazaar/requirements.txt
- thehive-templates/MalwareBazaar_1_0/long.html
- thehive-templates/MalwareBazaar_1_0/short.html
Address #722 
At the moment only search has been implemented because only bad sample can be submitted. Probably a responder for that feature will be better.
> malwarebazaar hash search

- analyzers/AnyRun/AnyRun_Sandbox_Analysis.json
- analyzers/AnyRun/anyrun_analyzer.py
- analyzers/AnyRun/requirements.txt
- thehive-templates/AnyRun_Sandbox_1_0/long.html
- thehive-templates/AnyRun_Sandbox_1_0/short.html
> add analyzer for any.run sandbox

- analyzers/Yeti/Yeti.json
- analyzers/Yeti/requirements.txt
- analyzers/Yeti/yeti.py
Fixes #468 adding verify_ssl parameter in conf
Fixes #708 moving pyeti library from python2 to python3
Fixes issue that returned error when item was not found in yeti
> fix multuple yeti issues

- analyzers/EmlParser/parse.py
Emlparser crashes when the string "Content-Type" is not found. In some cases it's available as "Content-type" or "content-type" , this fixes those cases
> Fix bug emlparser when 'content-type' string in mail is in lower case

- analyzers/DNSDB/Dockerfile
- analyzers/DNSDB/dnsdb.py
- analyzers/DNSDB/dnsdb_query.py
- analyzers/DNSDB/requirements.txt
based on #696 
check if response has status 200 and converts map object with list in order to be serializable
> fix on python3 compatibility for #696

- analyzers/OpenCTI/OpenCTI.json
- analyzers/OpenCTI/opencti.py
- analyzers/OpenCTI/requirements.txt
- thehive-templates/OpenCTI_SearchObservable_1_0/long.html
- thehive-templates/OpenCTI_SearchObservable_1_0/short.html
https://github.com/TheHive-Project/Cortex-Analyzers/issues/723
> Add OpenCTI Analyzer v1

- responders/RT4/README.md
- responders/RT4/__init__.py
- responders/RT4/config.py
- responders/RT4/requirements.txt
- responders/RT4/rt4.json
- responders/RT4/rt4.py
- responders/RT4/template.py
- responders/RT4/templates/malware.j2
- responders/RT4/templates/phishing_generic.j2
Satisfy issue #430 
Documented and used in production for a few months. This first public release represents v1.0 and some additional changes to what we've been using, so quirks are always possible.
> Add RT4-CreateTicket

- responders/SendGrid/SendGrid.json
- responders/SendGrid/SendGrid.py
- responders/SendGrid/requirements.txt
Adds SendGrid responder to deliver email via SendGrid HTTPS API
> Initial commit for SendGrid responder

- analyzers/SinkDB/SinkDB.json
- analyzers/SinkDB/sinkdb.py
- thehive-templates/SinkDB_1_0/long.html
> sinkdb: fqdn support

- analyzers/OTXQuery/otxquery.py
In python3 bytes and string are no longer the same thing.
Response.content returns bytes and json.loads expects string.
Reponse.text returns string and can be used instead of Response.content
> Use Response.text instead of Response.content

- responders/Shuffle/requirements.txt
- responders/Shuffle/shuffle.json
- responders/Shuffle/shuffle.py
Could add more datatypes, but that's for later. This could e.g. execute something specific for every alert or case that is added. Could be good for specific enrichments etc.
> Added Shuffle workflow execution responder

- analyzers/AnyRun/AnyRun_Sandbox_Analysis.json
- analyzers/AnyRun/anyrun_analyzer.py
Code to address FR:  https://github.com/TheHive-Project/Cortex-Analyzers/issues/853
> Included privacy type setting for URL/File analysis

- analyzers/TalosReputation/TalosReputation.py
- analyzers/TalosReputation/requirements.txt
- Added cloudscraper module and made requests with it to bypass Cloudflare protection when requesting details and location info.
- Updated requirements to use cloudscraper module.
> Fixes status_code 503 error caused by Cloudflare

- analyzers/Umbrella/Umbrella_Report.json
> Add fqdn to Umbrella analyzer

- responders/Mailer/mailer.py
TheHive4 does use equal signs instead of colons for tags
See issue: https://github.com/TheHive-Project/Cortex-Analyzers/issues/847
> TheHive4: equal signs instead of colons for tags

- analyzers/CIRCLPassiveSSL/circl_passivessl.py
Solution for:
- https://github.com/TheHive-Project/Cortex-Analyzers/issues/805
> added check to validate that hash is in subject table

- responders/VirustotalDownloader/VirustotalDownloader.py
Some fixes to virustotal download reponder.
If the type was not guessed properly it returned error, now keep the original hash as filename.
The case id was taken from `case_id = self.get_param('data._parent')` but that was None since the original input don't have that parameter. Now is taken from `case_id = self.get_param("data.case._id")`
Input eg: 
Output eg:
@hariomenkel , since you wrote original code can you please check if everything is ok? thanks
> fix case id, error if type is not guessed

- analyzers/Elasticsearch/ElasticSearch.json
- analyzers/Elasticsearch/elk.py
- analyzers/Elasticsearch/requirements.txt
- thehive-templates/Elasticsearch/long.html
- thehive-templates/Elasticsearch/short.html
Query any ElasticSearch cluster or multiple clusters for any field and any index and return common fields that use the ElasticSearch Common Schema (ECS)
#841
> [New Analyzer] Elasticsearch Analyzer

- analyzers/MnemonicPDNS/pdns.py
The current API URI to mnemonics PDNS service is deprecated/unsupported, and will be removed.
> Update mnemonic pdns.py with correct API URI

- responders/CheckPoint/CheckPoint_Gaia_lock.json
- responders/CheckPoint/CheckPoint_Gaia_unlock.json
- responders/CheckPoint/README.md
- responders/CheckPoint/checkpoint.py
- responders/CheckPoint/requirements.txt
The responder uses CheckPoint [python API](https://github.com/CheckPointSW/cp_mgmt_api_python_sdk) and permits to add or remove an ip from a specific group.
API must grant access to cortex machine and initial fingerprint must be generated somehow.
> Add CheckPoint Responder

- analyzers/TorProject/tor_project.py
- analyzers/TorProject/tor_project_analyzer.py
> Add proxies support to torproject analyzer

- thehive-templates/VirusTotal_Scan_3_0/long.html
For VirusTotal_Scan long report summary, check if content.permalink
exists, and use that to link back to VirusTotal report instead of
hand-crafted link, only when the scan was a scan of a URL.
I don't know why the template had the link back only set for URL scans, however, I found that all types of scans seem to provide a permalink, so I only check if content.permalink exists, and if so, use that as the link back to VirusTotal.
Additionally I also observed, that the former hand crafted link back to VirusTotal did not worked for all URL scans.
> Change the link back to VirusTotal Template using content.permalink

- analyzers/URLhaus/URLhaus_analyzer.py
- responders/AzureTokenRevoker/AzureTokenRevoker.json
- responders/AzureTokenRevoker/AzureTokenRevoker.py
- responders/AzureTokenRevoker/requirements.txt
Hello, please see the supplied AzureTokenRevoker responder .py, .json, and requirements.txt files.
Two outstanding issues within the responder's .py codew:
1.) I was not able to clear up, is what the get_params data path was for a submitted UPN within a case. Would it be "data.data"? Or something else?
2.) Will a self.report statement with a message be sufficient as a return of success? Or is there some other object I should be passing back to TheHive?
> [OSCD Initiative] Add Azure Authentication Token Revokation Responder

- analyzers/StamusNetworks/StamusNetworks_IPInfo.json
- analyzers/StamusNetworks/hostid_analyzer.py
- analyzers/StamusNetworks/requirements.txt
- thehive-templates/StamusNetworks_HostID_1_0/long.html
- thehive-templates/StamusNetworks_HostID_1_0/short.html
[Scirius Security Platform](https://www.stamus-networks.com/scirius-platform) (SSP) is a network threat detection solution based on Suricata. One of the features of SSP is the capability to build and maintain host identity card for the hosts in the network. This data are accessible via a REST API. By using this data, the analyzer can create some artifacts such as fqdn and get other information such as used user agent, username seen on the host.
Scirius Security Platform is a per organization product so users of the analyzer will need to point the analyzer to their own instance of SSP running and analyzing their network.
See description in d4ccae4 for information about the data structure.
Implement https://github.com/TheHive-Project/Cortex-Analyzers/issues/958.
> Scirius Security Platform Host ID analyzer

- responders/Mailer/requirements.txt
The requirements.txt file seems to be missing resulting in the bug below
https://github.com/TheHive-Project/Cortex/issues/334
> Mailer Responder | Create requirements.txt

- analyzers/FalconSandbox/FalconSandbox.json
- analyzers/FalconSandbox/FalconSandbox.py
- analyzers/FalconSandbox/long.html
- analyzers/FalconSandbox/requirements.txt
- analyzers/FalconSandbox/short.html
I added a Cortex Analyzer to push files to the Crowdstrike Falcon X Sandbox and get the report back.
This addresses the issue "Analyzer for Crowdstrike Falcon X - Sandbox #796"
https://github.com/TheHive-Project/Cortex-Analyzers/issues/796#issue-641138554
Changes to be committed:
new file:   analyzers/FalconSandbox/FalconSandbox.json
new file:   analyzers/FalconSandbox/FalconSandbox.py
new file:   analyzers/FalconSandbox/long.html
new file:   analyzers/FalconSandbox/requirements.txt
new file:   analyzers/FalconSandbox/short.html
added by Sebastian Schmerl (sebastian.schmerl@gmail.com)
> Added a Analyzer for Crowdstrikes Falcon X Sandbox

- responders/Velociraptor/README.md
- responders/Velociraptor/velociraptor_flow.json
- responders/Velociraptor/velociraptor_flow.py
- Adds the ability to upload flow results as a case observable.
- Other improvements
> Velociraptor: Add upload functionality for flow results

- analyzers/EmlParser/EmlParser.json
- analyzers/EmlParser/parse.py
Added features:
- sanitized mail rendering when it fails
- new tags for artifacts
- `autoImport:True` on some artifacts
> Improved emlParser

- analyzers/Maltiverse/Maltiverse_Report.json
- analyzers/Maltiverse/maltiverse-client.py
This PR adds an authentication parameter within the Maltiverse analyzer so you can use your subscription from the platform.
> Add authentication option for Maltiverse

- thehive-templates/SEKOIAIntelligenceCenter_Context_1_0/long.html
- thehive-templates/SEKOIAIntelligenceCenter_Indicators_1_0/long.html
- thehive-templates/SEKOIAIntelligenceCenter_Observables_1_0/long.html
Improve the report templates with the following improvements:
* Display the object's ID
* Display the revocation status
* Indicate when the object is a source or a sector
I didn't know if you should have created a PR against master or develop, if needed I can change it :)
> feat: Improve templates for SEKOIA analyzers

- .github/workflows/build.yml
- analyzers/FileInfo/Dockerfile
- analyzers/FileInfo/requirements.txt
- utils/test_doc/requirements.txt
- remove `.drone.yml`
- Replace workflow with github action jobs
- On tag it will: 
- publish images to docker hub (and harbor)
- create a release on github
Breaking Change:
- new catalog is no longer uploaded to package server
> Use github actions for CI

- analyzers/OpenCTI/opencti.py
Everything is explained in #1182
> Editing bug related to https://github.com #1182

- analyzers/SEKOIAIntelligenceCenter/sekoia_intelligence_center_analyzer.py
- thehive-templates/SEKOIAIntelligenceCenter_Context_1_0/long.html
- thehive-templates/SEKOIAIntelligenceCenter_Indicators_1_0/long.html
- thehive-templates/SEKOIAIntelligenceCenter_Observables_1_0/long.html
Fixes added to the Sekoia.io analyzers:
- Add a taxonomy observables known in Sekoia.io without indicated threats
- Fix long report templates - reports were not displayed when the analyzer returns more than 1 result
> Fix analyzer and long report templates

- analyzers/Crowdsec/requirements.txt
Add "requests" in `requirements.txt` file in CrowdSec Analyzer.
Fix #1173
> Fix missing requirements.txt in CrowdSec Analyzer

- analyzers/StamusNetworks/hostid_analyzer.py
This was causing the analyzers to fail on some valid entries.
> StamusNetworks: fix error on empty network info

- analyzers/Gatewatcher_CTI/Gatewatcher_CTI.py
- analyzers/Gatewatcher_CTI/README.md
We update the value (score) to build taxonomy and add more information in the README
> Update Gatewatcher CTI Analyzer for 'unknown' risk

- responders/EclecticIQIndicator/Dockerfile
- responders/EclecticIQIndicator/EclecticIQIndicator.json
- responders/EclecticIQIndicator/EclecticIQIndicator.py
- responders/EclecticIQIndicator/requirements.txt
Refer issue [#1257 ](https://github.com/TheHive-Project/Cortex-Analyzers/issues/1257)
> EclecticIQ responder

- analyzers/KasperskyTIP/KasperskyTIP.py
Every time an observable is classified in the Orange zone, it is tagged as "Info". As per the documentation [here](https://opentip.kaspersky.com/Help/Doc_data/AboutZones.htm), it should be classified as Malicious.
> KasperskyTIP fix: previously ignored category orange now is malicious

- analyzers/SpamhausDBL/spamhausdbl.py
The query() function does not work anymore with recent versions of Python (as it is in the containerized neuron). It was replaced with the resolve() function, which makes the analyzer work again as expected.
> SpamHausDBL fix: replace query function (not working) with resolve function

- responders/Cloudflare_IP_Blocker/CloudflareIPBlocker.json
- responders/Cloudflare_IP_Blocker/CloudflareIPBlocker.py
- responders/Cloudflare_IP_Blocker/requirements.txt
Hi!
Contributing with responder that allows to add Cloudflare Account IP Access list entry and block/challenge/whitelist any IP from case observables.
Supports multiple accounts as input.
API Documentation: https://developers.cloudflare.com/api/operations/ip-access-rules-for-an-account-create-an-ip-access-rule
> Cloudflare Account IP Access List Responder

- analyzers/NERD/README.md
- analyzers/NERD/nerd.json
- analyzers/NERD/nerd_analyzer.py
- added support for "whitelist" tag (i.e. IPs whitelisted in NERD shows as such in Cortex)
- better error handling, distinguish 404 because of unknown IP address from other reasons (e.g. wrong base_url)
- README updated
- version set to 1.1
Fully tested on my Cortex instance.
> Update of NERD analyzer

- responders/FalconCustomIOC/Dockerfile
- responders/FalconCustomIOC/FalconCustomIOCv2.json
- responders/FalconCustomIOC/FalconCustomIOCv2.py
- responders/FalconCustomIOC/requirements.txt
Hello,
As the Swagger API create_ioc & IOCs endpoint are now deprecated (issue #904), the previous Falcon responser does not work anymore. But I’ve been able to rebuilt it (based on  [ag-michael](https://github.com/ag-michael) previous work) using the [new IOC.indicator_create() method from falconpy](https://www.falconpy.io/Service-Collections/IOC.html#indicator_create_v1) instead. Here are some modifications I’ve added to this responder:
Choice of the severity level when IOCs are ingested by Falcon CustomIOC:
- informational
- low
- medium
- high (default)
- critical
Choice of how the IOCs are ingested by Falcon CustomIOC: 
- no_action: Save the indicator for future use, but take no action. No severity required.
- detect: Enable detections for the indicator at the selected severity. …
> FalconCrowstrikeCustomIOC Responder v2

- responders/MSDefenderEndpoints/Dockerfile
- responders/MSDefenderEndpoints/MSDefenderEndpoints.py
- responders/MSDefenderEndpoints/MSDefenderEndpoints_AutoInvestigation.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_Isolate.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_PushIOCAlert.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_PushIOCBlock.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_RestrictAppExecution.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_UnRestrictAppExecution.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_Unisolate.json
- responders/MSDefenderEndpoints/MSDefenderEndpoints_VirusScan.json
- responders/MSDefenderEndpoints/README.md
This PR contains a few fixes for this responder :
- When an organisation doesn't synchronise computers in AzureAD, the function getMachineID is not able to retrieve an id as the field AadDeviceID returns null. In this case, it retrieves the field id, which is an id provided by MDE to the machine.
- We had issues with the oauth uri, and updated the uri provided in the json files with the latest one on MS's documentation.
- Fixed the Dockerfile as the -r option was causing issues during the build.
- Fixed the malformed json body of the pushCustomIOCAlert function.
**New Features :** 
- You can now lauch an automated investigation on a device
- You can restrict the exectution of apps on the device (leaves Outlook, skype, Teams operational). Not as restrictive as device isolation. A tag is …
> Fixes and added features to Defender for endpoints responder

- responders/MailIncidentStatus/requirements.txt
- responders/PaloAltoNGFW/requirements.txt
- responders/Velociraptor/requirements.txt
- responders/VirustotalDownloader/requirements.txt
Fixes #1281: Pin the version of thehive4py to 1.8.x to ensure compatibility. This change uses the version specifier ~=1.8.1 in all requirements.txt files to allow updates within the 1.8 minor series, while avoiding breaking changes in future major versions.
> Pin thehive4py package version to 1.8.x

- analyzers/HybridAnalysis/HybridAnalysis_GetReport.json
- analyzers/HybridAnalysis/HybridAnalysis_analyzer.py
Fixing HybridAnalysis analyzer that was not working since API V2 :
- Fix added
- API Secret not needed anymore in configuration (only API Key)
- Adding possibility to analyze URL or Domain
> [FIX] HybridAnalysis API V2

- analyzers/AnyRun/AnyRun_Sandbox_Analysis.json
- analyzers/AnyRun/README.md
- analyzers/AnyRun/anyrun_analyzer.py
Have updated the Any.Run sandbox analyzer to accept more parameters, allowing customization of run-types.
> AnyRun Sandbox Analyzer v1.1

- analyzers/Abuse_Finder/requirements.txt
Abuse finder was recently made compatible with current python versions. Reflecting the change here
This should fix https://github.com/TheHive-Project/Cortex/issues/352 and https://github.com/TheHive-Project/Cortex-Analyzers/issues/940
> bump abuse_finder

- analyzers/TorBlutmagie/TorBlutmagie.json
- analyzers/TorBlutmagie/tor_blutmagie.py
TorBlutMagie has been taken down since 2018 this will fix it by using an alternative domain that exports the same information. I can rework the Analyser if required to be refereed to as the new domain however I left it as is for the moment so people who may have used it understand it is the same tool and should work the same way besides referencing a different domain.
> Update TorBlutMagie to point to alternative domain

- analyzers/DNSdumpster/DNSdumpster.json
- analyzers/DNSdumpster/README.md
- analyzers/DNSdumpster/dnsdumpster.py
- analyzers/DNSdumpster/requirements.txt
Cortex analyzer for DNSdumpster. Fixed #1056
> DNSdumpster analyzer. Initial commit.

- responders/Duo_Security/DuoBypassUserAccount.json
- responders/Duo_Security/duoBypassUserAccount.py
Pull Request #1201 
I did some git organizing on my repo's end and the initial PR is no longer correct.
> Duo Account Bypass Mode (Correction)

- responders/RT4/requirements.txt
Running the RT4 responder in Docker throws a ModuleNotFound error.: 
Traceback (most recent call last):
File "/worker/RT4/rt4.py", line 4, in <module>
from cortexutils.responder import Responder
ModuleNotFoundError: No module named 'cortexutils'
Is it possible to correct this Docker image present in the Docker Hub repository ?
> cortexutils not installed in RT4 Responder Docker Image

- responders/Netcraft/Dockerfile
- responders/Netcraft/Netcraft.py
- responders/Netcraft/NetcraftTakedown.json
- responders/Netcraft/README.md
- responders/Netcraft/requirements.txt
Cortex responder for Netcraft Takedown service. Fixes #1052
> Netcraft Cortex responder

- responders/AWX/awx.json
- responders/AWX/awx.py
- responders/AWX/requirements.txt
Simple starter for Ansible AWX Jobs #1213
> Added responder for Ansible AWX

- analyzers/DomainTools/requirements.txt
- analyzers/DomainToolsIris/requirements.txt
Analyzers do not work with latest versions of domaintools-api, whether it is domaintools-api 1.x or 2.x
> Domaintools dependency issues

- analyzers/Capa/Dockerfile
- analyzers/Capa/fetch_capa.sh
This PR:
- Removes the need to keep the capa binary in the repository.
- Implements an auto-download mechanism to fetch the latest capa binary during each build.
> Capa Analyzer - auto-download latest capa binary

- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_GetDeviceVulnerabilities.py
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox.py
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_getDeviceAlerts.py
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_getDeviceDetails.py
- responders/CrowdstrikeFalcon/CrowdstrikeFalconHosts.py
- responders/CrowdstrikeFalcon/CrowdstrikeFalconIOC.py
- responders/CrowdstrikeFalcon/CrowdstrikeFalconSync.py
This pull request implements the custom `User-Agent` header for all our Crowdstrike Falcon supported analyzers/responders, allowing all API requests to include the header `strangebee-thehive/1.0`.
Closes #1306
> CrowdStrike Falcon - Implement TheHive custom user-agent across integrations

- analyzers/ValidateObservable/README.md
- analyzers/ValidateObservable/ValidateObservable.json
- analyzers/ValidateObservable/ValidateObservable.py
- analyzers/ValidateObservable/requirements.txt
- thehive-templates/ValidateObservable_1_0/long.html
> Add ValidateObservable analyzer

- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_GetDeviceVulnerabilities.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_GetDeviceVulnerabilities.py
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox.py
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_Android.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_Linux.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_MacOS.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_Win10.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_Win11.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_Win7.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_Sandbox_Win7_64.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_getDeviceAlerts.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_getDeviceAlerts.py
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_getDeviceDetails.json
- analyzers/CrowdstrikeFalcon/CrowdstrikeFalcon_getDeviceDetails.py
- responders/CrowdstrikeFalcon/CrowdStrikeFalcon_AddIOC.json
- responders/CrowdstrikeFalcon/CrowdStrikeFalcon_Sync.json
- responders/CrowdstrikeFalcon/CrowdStrikeFalcon_removeIOC.json
- responders/CrowdstrikeFalcon/CrowdstrikeFalconHosts.py
- responders/CrowdstrikeFalcon/CrowdstrikeFalconIOC.py
- responders/CrowdstrikeFalcon/CrowdstrikeFalconSync.py
- responders/CrowdstrikeFalcon/CrowdstrikeFalcon_containHost.json
- responders/CrowdstrikeFalcon/CrowdstrikeFalcon_hideHost.json
- responders/CrowdstrikeFalcon/CrowdstrikeFalcon_liftContainmentHost.json
- responders/CrowdstrikeFalcon/CrowdstrikeFalcon_suppressDetections.json
- responders/CrowdstrikeFalcon/CrowdstrikeFalcon_unhideHost.json
- responders/CrowdstrikeFalcon/CrowdstrikeFalcon_unsuppressDetection.json
This PR adds custom base URL support for Crowdstrike Falcon analyzers & responders
Closes #1309
> Crowdstrike Falcon - Custom Base URL support

- utils/docker/build.sh
- utils/flavors/README.md
- utils/flavors/flavor_schema.json
- utils/flavors/requirements.txt
- utils/test_doc/README.md
- utils/test_doc/testdoc-venv.sh
Better documentation + added required requirements
> utils improvements

- .github/workflows/build.yml
- Updated actions/upload-artifact@v3 → v4 (fixes deprecation warning).
- Updated actions/checkout@v3 → v4 
- Updated actions/setup-python@v3 → v5 (latest stable version).
> CI - Fixes and improvements

- analyzers/OTXQuery/otxquery.py
* add IDS detection information
* report alerts
* return 'No alerts available' when that is the case
* only add alerts if they are available
* return ids_detections only if available
> OTX query does not have actionable intelligence

- responders/Velociraptor/README.md
- responders/Velociraptor/requirements.txt
- responders/Velociraptor/velociraptor_flow.json
- responders/Velociraptor/velociraptor_flow.py
For SaaS deployments, you can now encode your API client config:
```bash
cat api_client.yaml | base64
```
Then paste the output into the `velociraptor_client_config_content_base64` parameter.
> Velociraptor - support for b64 api configuration for SaaS deployments
