TheHive-Project/Cortex-Analyzers

analyzers/VirusTotal/virustotal.py
For https://github.com/CERT-BDF/TheHive/issues/177 - sorry, wrong repo, there.
=> Added rate limit message for VirusTotal analyzer

thehive-templates/VirusTotal_GetReport_3_0/long.html
VT external links seem to have changed format, I updated them.
=> Updated VT links in Long report

thehive-templates/VirusTotal_GetReport_3_0/long.html
Reverts CERT-BDF/Cortex-Analyzers#98
=> Revert "Updated VT links in Long report"

analyzers/MISP/misp.py, analyzers/MISP/mispclient.py
Please review it in detail, because I don't have a TheHive environment at home.
=> Fixes MISP Analyzer name bug

analyzers/Shodan/Shodan_Host.json, analyzers/Shodan/Shodan_Search.json, analyzers/Shodan/shodan_analyzer.py, analyzers/Shodan/shodan_api.py, thehive-templates/Shodan_Host_1_0/long.html, thehive-templates/Shodan_Host_1_0/short.html, thehive-templates/Shodan_Search_1_0/long.html, thehive-templates/Shodan_Search_1_0/short.html
=> add Analyzers Shodan

analyzers/Robtex/.gitignore, analyzers/Robtex/Robtex_Forward_PDNS_Query.json, analyzers/Robtex/Robtex_IP_Query.json, analyzers/Robtex/Robtex_Reverse_PDNS_Query.json, analyzers/Robtex/requirements.txt, analyzers/Robtex/robtex.py, thehive-templates/Robtex_Forward_PDNS_Query_1_0/long.html, thehive-templates/Robtex_Forward_PDNS_Query_1_0/short.html, thehive-templates/Robtex_IP_Query_1_0/long.html, thehive-templates/Robtex_IP_Query_1_0/short.html, thehive-templates/Robtex_Reverse_PDNS_Query_1_0/long.html, thehive-templates/Robtex_Reverse_PDNS_Query_1_0/short.html
=> Robtex API Analyzer

thehive-templates/MISPWarningLists_1_0/long.html
=> MISP WarningLists reports

analyzers/CyberCrimeTracker/CyberCrimeTracker.json, analyzers/CyberCrimeTracker/cct.py, analyzers/CyberCrimeTracker/requirements.txt, thehive-templates/CyberCrimeTracker_1_0/long.html, thehive-templates/CyberCrimeTracker_1_0/short.html
=> cybercrime-tracker.net analyzer

analyzers/Mnemonic_pdns/mnemonic_pdns_closed.json, analyzers/Mnemonic_pdns/mnemonic_pdns_public.json, analyzers/Mnemonic_pdns/pdns.py, analyzers/Mnemonic_pdns/requirements.txt, thehive-templates/Mnemonic_PDNS_closed_3_0/long.html, thehive-templates/Mnemonic_PDNS_closed_3_0/short.html, thehive-templates/Mnemonic_pDNS_public_3_0/long.html, thehive-templates/Mnemonic_pDNS_public_3_0/short.html
Referencing to #255. Created Mnemonic PDNS public and closed analyzers.
=> Created Mnemonic PDNS public and closed analyzers

analyzers/GreyNoise/GreyNoise.json, analyzers/GreyNoise/greynoise.py, analyzers/GreyNoise/requirements.txt
Creating a new analyzer for GreyNoise.
https://github.com/GreyNoise-Intelligence/api.greynoise.io
Referencing #231
=> GreyNoise analyzer

analyzers/ProofPoint/Long_ReportTemplate.txt, analyzers/ProofPoint/ProofPoint_Lookup.json, analyzers/ProofPoint/proofpoint_lookup.py
Hello,
I have created a cortex analyzer for querying ProofPoint Threat Insight Forensics API.
It is needed to be a proofpoint customer with an API access to Threat Insight Dashboard.
By using the Forensics API you can search for sha256, file, URL and get proofpoint forensics analysis if observable is already known.
API information can be find [here](https://help.proofpoint.com/Threat_Insight_Dashboard/API_Documentation)
Regards,
=> ProofPoint Threat Insight Forensics Analyzer

thehive-templates/PassiveTotal_Passive_Dns_2_0/long.html
=> PassiveTotal_Passive_Dns_2_0: Improve the ordering of the records

analyzers/Virusshare/getHashes.sh
=> fix: "cut: the delimiter must be a single character"

analyzers/HIBP_Query/HIBP_Query.json, analyzers/HIBP_Query/hibpquery_analyzer.py, analyzers/HIBP_Query/input, thehive-templates/HIBP_Query_1_0/long.html, thehive-templates/HIBP_Query_1_0/short.html
Added HIBP Analyzer with templates
=> Added HIBP Analyzer with templates

analyzers/HIBP_Query/HIBP_Query.json, analyzers/HIBP_Query/hibpquery_analyzer.py
Add the configuration option to include unverified breaches.
[Breaches for All Accounts](https://haveibeenpwned.com/API/v2#BreachesForAccount)
[Unverified Breaches](https://haveibeenpwned.com/FAQs#UnverifiedBreach)
=> HIBP_Query - Option to include Unverified Breaches

analyzers/SecurityTrails/SecurityTrails_Passive_DNS.json, analyzers/SecurityTrails/SecurityTrails_Whois.json, analyzers/SecurityTrails/requirements.txt, analyzers/SecurityTrails/securitytrails.py, analyzers/SecurityTrails/securitytrails_analyzer.py, thehive-templates/SecurityTrails_Passive_DNS_1.0/long.html, thehive-templates/SecurityTrails_Passive_DNS_1.0/short.html, thehive-templates/SecurityTrails_Whois_1.0/long.html, thehive-templates/SecurityTrails_Whois_1.0/short.html
add SecurityTrails Passive DNS & Whois analyzers. (#370)
**Passive DNS**
**Whois**
=> feat: add SecurityTrails analyzers

analyzers/Malwares/malwares_api.py
=> make code python 3.4 compatible

thehive-templates/Cymon_2_1/long.html
=> Fix a broken link in the Cymon_Check_IP report

thehive-templates/AbuseIPDB_1_0/long.html, thehive-templates/AbuseIPDB_1_0/short.html
Related to #400.
Forgive me but I don't use The Hive, I'm just a Cortex user and, sincerely, I didn't get the chance to test them. However I followed other templates scheme. If you can check if it works before merging it would help. thanks
=> added templates for AbuseIPDB

analyzers/Yeti/yeti.py
Optionally, we can provide a yeti apy_key. If so, we would need to modify the Yeti.json accordingly
=> Possibility to use a Yeti apikey.

analyzers/Yeti/Yeti.json
=> yeti api key

analyzers/DNSSinkhole/DNSSinkhole.json, analyzers/DNSSinkhole/dnssinkhole.py, analyzers/DNSSinkhole/requirements.txt, thehive-templates/DNSSinkhole_1_0/long.html, thehive-templates/DNSSinkhole_1_0/short.html
=> added custom Dns sinkholed ip

analyzers/Fortiguard/urlcategory.py
This PR gives a fix to #491. I am sorry to not give more input about how to reproduce this :s.
=> Use req.text instead of req.content

responders/DNS-RPZ/DNS-RPZ.json, responders/DNS-RPZ/dns-rpz.py, responders/DNS-RPZ/requirements.txt
Added the DNS-RPZ responder from feature request #435.
=> Add responder DNS-RPZ (issue #435)

analyzers/JoeSandbox/joesandbox_analyzer.py, analyzers/JoeSandbox/requirements.txt
Use official jbxapi  (https://github.com/joesecurity/jbxapi)
Support only for jbxapi v3  and  latest JoeSandbox v26 Aquamarine
Co-Authored-By: Arcuri Davide <dadokkio@gmail.com>
=> updated joesandbox analyzer

responders/FalconCustomIOC/requirements.txt
Remove builtin python modules from `requirements.txt`
=> remove builtin modules from requirements.txt

analyzers/EmailRep/emailrep_analyzer.py, thehive-templates/EmailRep_1_0/long.html
Catch up the latest API response schema (Ref. #467)
=> Update EmailRep analyzer

analyzers/Shodan/Shodan_DNSResolve.json, analyzers/Shodan/Shodan_InfoDomain.json
added fqdn to shodan - patial fix for #350
=> fix for Shodan

analyzers/Threatcrowd/Threatcrowd.json, analyzers/Threatcrowd/threatcrowd_analyzer.py
added fqdn to threatcrowd - partial fix for #350
=> fix for threatcrowd

analyzers/VirusTotal/VirusTotal_GetReport.json, analyzers/VirusTotal/virustotal.py
added fqdn to search - partial fix for #350
=> fix for virus total

analyzers/IPVoid/IPVoid.json, analyzers/IPVoid/ipvoid.py, analyzers/IPVoid/requirements.txt, thehive-templates/IPVoid_1_0/long.html, thehive-templates/IPVoid_1_0/short.html
=> Added IPVoid IP reputation API analyzer 

analyzers/URLhaus/URLhaus.json, analyzers/URLhaus/URLhaus_analyzer.py
As suggested in https://github.com/TheHive-Project/Cortex-Analyzers/pull/556
=> fqdn  support for Url haus

analyzers/ProofPoint/requirements.txt, analyzers/SpamhausDBL/requirements.txt, analyzers/TeamCymruMHR/requirements.txt, analyzers/Umbrella/requirements.txt, responders/FalconCustomIOC/requirements.txt, responders/KnowBe4/requirements.txt, responders/Minemeld/requirements.txt, responders/Wazuh/requirements.txt
As described in https://github.com/TheHive-Project/Cortex-Analyzers/issues/695
Added cortexutils in all requirements.txt
Thanks @milesflo
=> cortexutils in all requirements.txt

analyzers/Threatcrowd/threatcrowd_analyzer.py
Reverts TheHive-Project/Cortex-Analyzers#518
=> Revert "[ThreatCrowd ] Fixing Unexpected Error: get() takes exactly 1 argument (2 given)"

analyzers/MISPWarningLists/mispwarninglists.py
CortexUtil changed Extractor return keys on 4th April
https://github.com/TheHive-Project/cortexutils/commit/f63222df1744c40e17becc2719f1337c5251e6d5#diff-8bfea30ee07c21ace8c48037f4b8457e
=> Fix - updated cortexutil Extractor return keys

analyzers/Shodan/shodan_analyzer.py, thehive-templates/Shodan_InfoDomain_1_0/long.html
=> fix infos_domain key in shodan

analyzers/CyberChef/CyberChefFromBase64.json, analyzers/CyberChef/CyberChefFromCharCode.json, analyzers/CyberChef/CyberChefFromHex.json, analyzers/CyberChef/cyberchef.py, analyzers/CyberChef/long.html, analyzers/CyberChef/requirements.txt, analyzers/CyberChef/short.html
Adds CyberChef analyzer (utilizes CyberChef server) capable of transforming the following types of data for the `other` field:
- Base64
- Hex
- CharCode
=> Add CyberChef Analyzer

analyzers/DomainToolsIris/domaintoolsiris_analyzer.py, thehive-templates/DomainToolsIris_Investigate_1_0/long.html, thehive-templates/DomainToolsIris_Pivot_1_0/long.html
Updating URLs in the analyzer reports because they point to old URLs.
=> DomainTools Iris Analyzer Report Updates

responders/Mailer/Mailer.json, responders/Mailer/mailer.py
Fixes wrong label in error: #379 
Adds smtp authentication: #737 
Merge tasks supports from #757
=> Add auth to Mailer and support for tasks

analyzers/ThreatResponse/ThreatResponse.py
=> #759 module_type removed in ThreatResponse

responders/Minemeld/requirements.txt
=> add requests to requirements

analyzers/MISPWarningLists/requirements.txt, analyzers/MISPWarningLists/warninglists_create_db.py, responders/Minemeld/minemeld.py
=> [Bug] MineMeld responder domain IOC incorrect type #892

analyzers/Splunk/splunk.py
=> FIX issue #896

thehive-templates/VirusTotal_GetReport_3_0/long.html
similar to VirusTotal_Scan, use the content.permalink to link back to the full report
=> update full report link for VirusTotal GetReport Template

analyzers/VirusTotal/VirusTotal_DownloadSample.json, analyzers/VirusTotal/VirusTotal_Rescan.json, analyzers/VirusTotal/VirusTotal_Scan.json, analyzers/VirusTotal/requirements.txt, analyzers/VirusTotal/virustotal.py
=> virustotal flow

thehive-templates/MISP_2_1/long.html
=> use tab for multiple misp instance in template

analyzers/GRR/GRR.json, analyzers/GRR/grrclient.py, analyzers/GRR/requirements.txt, analyzers/JoeSandbox/joesandbox_analyzer.py
Simple analyzer for GRR that checks and map the GRR client_id of an IP / FQDN
=> Simple analyzer for GRR

thehive-templates/EmailRep_1_0/long.html, thehive-templates/Fortiguard_URLCategory_2_1/long.html, thehive-templates/HybridAnalysis_GetReport_1_0/long.html, thehive-templates/IntezerCommunity_1_0/long.html, thehive-templates/Maltiverse_Report_1_0/long.html, thehive-templates/OTXQuery_2_0/long.html, thehive-templates/PassiveTotal_Malware_2_0/long.html
Mostly fixing URLs to upstream websites, or actually create a link instead of only printing it.
And some other minor enhancements, adding additional info to the report, or hide empty stuff.
=> A number of small enhancements to TheHive templates

analyzers/IP-API/IP-API.json, analyzers/IP-API/IP-API.py, analyzers/IP-API/requirements.txt, thehive-templates/IP-API_1_0/long.html, thehive-templates/IP-API_1_0/short.html
Checks IP address or domain using ip-api.com. Returns geolocation informations of IP address or domain. #1001
=> IP-API analyzer

analyzers/IPinfo/ipinfo_analyzer.py
Add ASNType & Company info + privacy details.
=> Add additional taxonomy for IPinfo

analyzers/CheckPhish/CheckPhish.json, analyzers/CheckPhish/CheckPhish.py, analyzers/CheckPhish/CheckPhish_Submit.json, analyzers/CheckPhish/requirements.txt, thehive-templates/CheckPhish_1_0/long.html, thehive-templates/CheckPhish_1_0/short.html, thehive-templates/CheckPhish_Submit_1_0/long.html, thehive-templates/CheckPhish_Submit_1_0/short.html
Detailed analysis of URL via CheckPhish. Returns URL to analysis and screenshot of site. #997 
Firstly, you need to submit URL and use returned string to find match with CheckPhish database.
=> CheckPhish analyzer

analyzers/Verifalia/Verifalia.json, analyzers/Verifalia/Verifalia.py, analyzers/Verifalia/requirements.txt, thehive-templates/Verifalia_1_0/long.html, thehive-templates/Verifalia_1_0/short.html
Submit e-mail address for analysis via Verifalia. Returns basic informations about analyzed e-mail address. #1007
=> Verifalia analyzer

analyzers/BitcoinAbuse/BitcoinAbuse.json, analyzers/BitcoinAbuse/BitcoinAbuse.py, analyzers/BitcoinAbuse/requirements.txt, thehive-templates/BitcoinAbuse_1_0/long.html, thehive-templates/BitcoinAbuse_1_0/short.html
Check Bitcoin address against Bitcoin Abuse database. Returns count of reports and description of reports. #995 
Need to create datatype _btc_address_.
=> Bitcoin Abuse analyzer

analyzers/ThreatMiner/ThreatMiner.json, analyzers/ThreatMiner/ThreatMiner.py, analyzers/ThreatMiner/requirements.txt, thehive-templates/ThreatMiner_1_0/long.html, thehive-templates/ThreatMiner_1_0/short.html
Returns WHOIS information of IP address or domain. #1005
=> ThreatMiner analyzer

analyzers/KasperskyTIP/KasperskyTIP.json, analyzers/KasperskyTIP/KasperskyTIP.py, analyzers/KasperskyTIP/requirements.txt, thehive-templates/KasperskyTIP_1_0/long.html, thehive-templates/KasperskyTIP_1_0/short.html
Analyze IP address, domain or hash via Kaspersky Threat Intelligence Portal. Returns basic informations about IP address, domain or hash. #1003
=> KasperskyTIP analyzer

analyzers/Crowdsec/crowdsec_api.py
This will help us with API usage metrics.
=> CrowdSec: Set user agent of crowdsec analyzer to crowdsec-cortex/v1.0.0

docs/dev_guides/how-to-test-an-analyzer.md
Fix to avoid json.decoder error
=> fix lacking json enclosure

.github/workflows/build.yml, analyzers/Maltiverse/Dockerfile, analyzers/Splunk/Dockerfile, responders/Jupyter_Responder/Dockerfile, responders/Jupyter_Responder/papermill_iorw.patch, utils/docker/Dockerfile_template
Fixes for:
- Splunk
- maltiverse
- Jupyter
=> Fix build for several analyzers & responders

analyzers/Jupyter_Analyzer/Jupyter_Run_Notebook_Analyzer.json, analyzers/MISP/MISP.json, analyzers/OpenCTI/OpenCTI_SearchExactObservable.json, analyzers/OpenCTI/OpenCTI_SearchObservables.json, analyzers/SoltraEdge/Soltra_search.json, analyzers/Splunk/Splunk_Search_mail_subject.json
Issue https://github.com/TheHive-Project/Cortex-Analyzers/issues/1260
=> add dataType mail-subject

analyzers/OpenCTI/opencti.py
https://docs.opencti.io/latest/reference/filters-migration/
=> Filters format migration for OpenCTI 5.12

responders/Shuffle/shuffle.py
added responder input to the API call so it will be the execution argument in the Shuffle workflow and can actually be used.
=> added responder input to Shuffle API call

analyzers/Censys/censys_analyzer.py
Censys has deprecated APIv1, so the current Censys analyzer isn't working,
here I have updated it to make sure it works using latest API package,
(I only tested IP enrichment and I made sure it works and produces taxonomies, but not the rest)
=> Updated Censys Analyzer for latest API

responders/Telegram/README.md, responders/Telegram/Telegram.json, responders/Telegram/requirements.txt, responders/Telegram/telegram.py
Hello!
This PR contains the Telegram responder.
It is related to issue https://github.com/TheHive-Project/Cortex-Analyzers/issues/1132
=> Add a responder to send case information to Telegram

responders/AzureTokenRevoker/AzureTokenRevoker.json, responders/AzureTokenRevoker/AzureTokenRevoker.py, responders/AzureTokenRevoker/README.md
=> Azure Token Revoker Responder

analyzers/LdapQuery/ldapQuery.py
When you want get datetime object for example whenCreated from domain you get error Object of type datetime is not JSON serializable.
=> When you get whenCreated attribute datetime fix

analyzers/DomainMailSPFDMARC/domainMailSPFDMARC_get_reports.json
Not compliant with https://github.com/TheHive-Project/CortexDocs/blob/master/api/how-to-create-an-analyzer.md#writing-templates
Template folder is named DomainMailSPFDMARC_1_1
=> Make analyzer work with template

analyzers/AnyRun/anyrun_analyzer.py
```
env:
Cortex3.1.8-1
cortexneurons/anyrun_sandbox_analysis
```
1. If you submit 'file' content to ANYRUN with anyrun_analyzer, you can met `Unexpected error: taskid` below.
2. I tested ANYRUN API with analyzer code and double checking ANYRUN API docs.
We need expected status code `201` and `['data']['taskid']` structure.
3. So, I request this pull for fix this issue. thx you
=> Fix anyrun_analyzer.py for submit file

analyzers/PhishTank/phishtank_checkurl.py
=> add proxies to phishtank_checkurl.py

analyzers/MSEntraID/MSEntraID.py, analyzers/MSEntraID/MSEntraID_GetDirectoryAuditLogs.json, analyzers/MSEntraID/MSEntraID_GetManagedDevicesInfo.json, analyzers/MSEntraID/MSEntraID_GetSignIns.json, analyzers/MSEntraID/MSEntraID_GetUserInfo.json, analyzers/MSEntraID/README.md, responders/MSEntraID/MSEntraID.py, responders/MSEntraID/MSEntraID_ForcePasswordReset.json, responders/MSEntraID/MSEntraID_ForcePasswordResetWithMFA.json, responders/MSEntraID/MSEntraID_TokenRevoker.json, responders/MSEntraID/MSEntraID_disableUser.json, responders/MSEntraID/MSEntraID_enableUser.json, responders/MSEntraID/README.md, thehive-templates/MSEntraID_GetDirectoryAuditLogs_1_0/long.html, thehive-templates/MSEntraID_GetManagedDevicesInfo_1_0/long.html, thehive-templates/MSEntraID_GetUserInfo_1_0/long.html
- Revised authentication
- New Password Reset responders (forceReset & force Reset with MFA)
- New Enable/Disable user responders
=> MSEntraID - Additional Analyzers & Responders + Improvements

responders/Mailer/mailer.py
Bug explained here: https://github.com/TheHive-Project/Cortex-Analyzers/issues/835
=> Mailer responder needs to be fixed when checking description

analyzers/IP-API/IP-API.json, analyzers/IP-API/IP-API.py, thehive-templates/IP-API_1_0/long.html, thehive-templates/IP-API_1_1/long.html, thehive-templates/IP-API_1_1/short.html
=> IP-API - Improvements & Pro license support

.github/workflows/build.yml, analyzers/EmlParser/Dockerfile, analyzers/EmlParser/requirements.txt, analyzers/Malpedia/Dockerfile, analyzers/Malpedia/requirements.txt
Complete CI Refactor for analyzers & responders :
- (Almost) no more remote TheHive-Project docker hub images in use for our CI
- CI all-in GitHub actions
- GHCR.io migration for our analyzers, responders, catalog
- ARM64 support
- Various improvements
=> CI Refactor - GHCR.io migration / ARM64 Support

analyzers/MSEntraID/MSEntraID.py, responders/MSEntraID/MSEntraID.py
=> MSEntra ID - Use GUIDs instead of UPNs for better compatibility

analyzers/Malwares/Malwares_Scan.json, analyzers/Malwares/malwares.py, analyzers/Malwares/malwares_api.py
Hi!
`https://www.ctx.io/about/api` is now incompatible with the Malwares analyzer. This PR aims to fix it
=> Fix analyzer: incompatible ctx.io api [Malwares]

analyzers/CIRCLVulnerabilityLookup/CIRCLVulnerabilityLookup.json, thehive-templates/DomainMailSPFDMARC_1_1/long.html
1. Fix for JA4
2. DomainMailSPFDMARC analyzer template improvements
=> Various small improvements

analyzers/MSEntraID/MSEntraID.py
- More reliable user resolution across different kinds of tenants
- Tentative fix for multiple devices lookup
- Improved filter logic for directory audit logs
=> MSEntraID - Enhancements & bug fixes

responders/Slack/Slack_CreateChannel.json, responders/Slack/requirements.txt, responders/Slack/slack.py
PR#1 for Slack Integration
Note: Documentation coming in another PR / batch of improvements
=> Slack integration - Create Channel / War room

responders/Mailer/mailer.py
=> Mailer - Tiny fixes & improvements

responders/Slack/README.md, responders/Slack/slack.py
- Add a tag when creating the channel
- Use tags for syncing
- Multiple channels sync in single case
=> Slack responder - Improvements
